#Maximum number of reservations a user can have active
maxActiveReservations: 4 

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: getaroom

  # the password
  password: getaroom

  # the JDBC URL
  url: jdbc:mysql://localhost/getaroom

server:
  rootPath: /api/
  
logging:
  level: INFO
  loggers:
    com.soen343: DEBUG
